%%  behaviorAD_all
% Calculates and plots the behavioral parameters for the comparison of WT
% and AD mice in a 6m active learning task. Can be adapted to any active
% learning task by modifying initialization parameters and how
% "fileTypes.mat" is processed. Virmen file categories are loaded from
% fileType.mat, which is generated by defineFiles.m.
%
% Analysis Days include:
%
%   1+ Familiar Environment Day: FE, Day -X to 0 (peak behavior day of
%       baseline imaging is day 0; others are the most recent non-imaging
%       days with at least 5 laps and no manual stopping)
%   10+ Novel Environment Days: NE, Days 1 to X; (days 1-10 are uses in
%       most plots regardless of whether imaging was successful)
%   1 Familiar Environment Recall Day: FER (actual day 12-13)
%   1 Novel Environment Recall Day: NER (actual day 17-18)
%
% Required paramters:
%   Genotype groups (currently loaded from groupIDs.mat)
%   FE and NE reward and false alarm (FA) locations
%   Bins for velocity distribution
%   Use laps (currently 2-20 to exclude first lap where mice are pushed)
%

clear; close all; clc


%% Initialize parameters

cd('D:\AD_Project\Behavior')
p = pwd;

% identify mouse folders
d = dir('TM*');
mID = {d(:).name}';

% read environment parameters
rewStart = [240 510];
rewStop = [290 560];
trackLength = 600;

% velocity distribution bins
velBins = -10:1:100;

% use laps
startLap = 2;
stopLap = 20;

% define reward zone sizes (amount removed from reward zone)
rewCut = 0:10:40;

% save folder
svFold = 'D:\AD_Project\Revision\Behavior\Results\';


%% Initialize behavior calculations

% behavior data struct (clear so fields don't need to be initialized)
clear B

% define day category names
typeFields = {'famLearn','novLearn','famRecall','novRecall','famPre'};

% define base variable/field names
namesStopCell = {'stopDist','yStopRew','perSuccess'};


%% Calculate behavioral parameters

for m = 1:length(mID)
    %% Process file info

    % move to current mouse directory
    cd(mID{m})

    % identify all virmen files
    d = dir('*T*.txt');
    fNames = {d(:).name}';

    % load file classification information
    load('fileType.mat','envType','type','typeLearn','typeAll');

    % define which track type each file corresponds to (files with no track
    % type are extra NE days, so are set to 2)
    envTrack = envType;
    envTrack(envTrack==0) = 2;


    %% Initialize data fields

    % initialize struct
    curB = struct();

    % set struct fields
    curB.type = type;
    curB.typeLearn = typeLearn;
    curB.typeAll = typeAll;

    % initialize struct fields
    for ii = 1:length(namesStopCell)
        curB.(namesStopCell{ii}) = cell(length(fNames),1);
    end


    %% Run behavior analysis for each session

    % loop through all files
    for ff = 1:length(fNames)
        %% Run analysis

        % load data (a .mat file will be created after the first load,
        % which will be loaded directly on future tuns)
        if ~isfile([fNames{ff}(1:end-4) '.mat'])
            logData = readLog(fNames{ff}, 9);
            params = logParams(logData);
            save([fNames{ff}(1:end-4) '.mat'],'params')
        else
            load([fNames{ff}(1:end-4) '.mat'])
        end

        % set environment parameters
        envParams = struct();
        envParams.rewStart = rewStart(envTrack(ff));
        envParams.rewStop = rewStop(envTrack(ff));
        envParams.trackLength = trackLength;

        % set use laps
        if envTrack(ff)==2
            % set use laps for novel environment days
            useLaps = startLap:stopLap;
        else
            % set use laps for familiar environment days
            useLaps = startLap:1000;
        end

        % calculate behavior
        behavior = extractActiveBehavior_rev(params,envParams,useLaps,rewCut);


        %% Extract results

        % extract cell based true stop statistics
        for jj = 1:length(namesStopCell)
            curB.(namesStopCell{jj}){ff} =behavior.(namesStopCell{jj});
        end

        % extract mouse and day
        curB.day{ff} = fNames{ff}(3:8);
        curB.mouse = split(mID{m},'\');

        % print file completion
        fprintf([num2str(m) '-' num2str(ff) '\n'])
    end

    % save current mouse data
    B(m) = curB;

    % change to parent directory
    cd(p)
end

% save combined data (match to load in next section)
save([svFold 'allMiceDataB5.mat'],'B','rewCut')

