%%  behaviorAD_all
% Calculates and plots the behavioral parameters for the comparison of WT
% and AD mice in a 6m active learning task. Can be adapted to any active
% learning task by modifying initialization parameters and how
% "fileTypes.mat" is processed. Virmen file categories are loaded from
% fileType.mat, which is generated by defineFiles.m.
%
% Analysis Days include:
%
%   1+ Familiar Environment Day: FE, Day -X to 0 (peak behavior day of
%       baseline imaging is day 0; others are the most recent non-imaging
%       days with at least 5 laps and no manual stopping)
%   10+ Novel Environment Days: NE, Days 1 to X; (days 1-10 are uses in
%       most plots regardless of whether imaging was successful)
%   1 Familiar Environment Recall Day: FER (actual day 12-13)
%   1 Novel Environment Recall Day: NER (actual day 17-18)
%
% Required paramters:
%   Genotype groups (currently loaded from groupIDs.mat)
%   FE and NE reward and false alarm (FA) locations
%   Bins for velocity distribution
%   Use laps (currently 2-20 to exclude first lap where mice are pushed)
%

clear; close all; clc


%% Initialize parameters

cd('D:\AD_Project\Behavior')
p = pwd;

% identify mouse folders
d = dir('TM*');
mID = {d(:).name}';

% read environment parameters
rewStart = [240 510];
rewStop = [290 560];
falseStart = [465 95];
trackLength = 600;

% velocity distribution bins
velBins = -10:1:100;

% use laps
startLap = 2;
stopLap = 20;

% learning threshold
dThresh = 1.0;

% predictive slowing thresholds
rewSlowPre = 90;
rewSlowPost = 80;
slowRuns = 0;
slowTrackStart = 0;
slowTrackEnd = trackLength;
movMeanSlow = 0;


%% Initialize behavior calculations

% behavior data struct (clear so fields don't need to be initialized)
clear B

% define day category names
typeFields = {'famLearn','novLearn','famRecall','novRecall','famPre'};

% define base variable/field names
namesStopNum = {'perSuccess','perSuccessWithStops','dprimeGlobal','successTile'...
    'dprime','dprimeWithStops','perStopsInReward','numStops','idxGoal'};
namesTryNum = {'perSuccessTry','dprimeTry','dprimeGlobalTry','successTileTry'};
namesVelNum = {'avgVelMovingRaw','avgVelAllRaw','avgVelMovingAbs',...
    'avgVelAllAbs','perTimeStopped'};
namesStopCell = {'successPerLap','stopTimeDist','stopTimeDist_NPR','yStartDistribution',...
    'yStartDistribution_NPR','stopDist','numStopsPerLap','numStopClustersPerLap',...
    'includeIdx','dprimeRoll','idxInclude','successRoll','avgVelMovingRawPerLap'};
nameVelCell = {'velMovingRaw','velMovingAbs','velDistMean','dwellDistMean'};

namesAll = {namesStopNum,namesTryNum,namesVelNum,namesStopCell,nameVelCell};


%% Calculate behavioral parameters

for m = 1:length(mID)
    %% Process file info

    % move to current mouse directory
    cd(mID{m})

    % identify all virmen files
    d = dir('*T*.txt');
    fNames = {d(:).name}';

    % load file classification information
    load('fileType.mat','envType','type','typeLearn','typeAll');

    % define which track type each file corresponds to (files with no track
    % type are extra NE days, so are set to 2)
    envTrack = envType;
    envTrack(envTrack==0) = 2;


    %% Initialize data fields

    % initialize struct
    curB = struct();

    % set struct fields
    curB.type = type;
    curB.typeLearn = typeLearn;
    curB.typeAll = typeAll;

    % initialize struct fields
    for ii = 1:length(namesAll)
        for jj = 1:length(namesAll{ii})
            if ii<4
                curB.(namesAll{ii}{jj}) = zeros(length(fNames),1);
            else
                curB.(namesAll{ii}{jj}) = cell(length(fNames),1);
            end
        end
    end

    % initialize predictive licking
    curB.predLicking = zeros(length(fNames),1);
    curB.predLickingAll = zeros(length(fNames),1);
    curB.licksAll = cell(length(fNames),1);
    curB.predSlowing = zeros(length(fNames),1);


    %% Run behavior analysis for each session

    % loop through all files
    for ff = 1:length(fNames)
        %% Run analysis

        % load data (a .mat file will be created after the first load,
        % which will be loaded directly on future tuns)
        if ~isfile([fNames{ff}(1:end-4) '.mat'])
            logData = readLog(fNames{ff}, 9);
            params = logParams(logData);
            save([fNames{ff}(1:end-4) '.mat'],'params')
        else
            load([fNames{ff}(1:end-4) '.mat'])
        end

        % set environment parameters
        envParams = struct();
        envParams.rewStart = rewStart(envTrack(ff));
        envParams.rewStop = rewStop(envTrack(ff));
        envParams.falseStart = falseStart(envTrack(ff));
        envParams.trackLength = trackLength;

        % set use laps
        if envTrack(ff)==2
            % set use laps for novel environment days
            useLaps = startLap:stopLap;
        else
            % set use laps for familiar environment days
            useLaps = startLap:1000;
        end

        % calculate behavior
        behavior = extractActiveBehavior(params,envParams,useLaps);
        licking = predLickActive(params,envParams,useLaps);
        lickingAlt = predLickActiveAlt(params,envParams,useLaps);
        slowing = predSlowingActive(params,envParams,rewSlowPre,rewSlowPost,...
            slowRuns,slowTrackStart,slowTrackEnd,movMeanSlow);


        %% Extract results

        % extract predictive licking
        curB.predLicking(ff,1) = licking.predLickPer;
        curB.predLickingAll(ff,1) = licking.perPredInAll;
        curB.predLickingAlt(ff,1) = lickingAlt.perPredInAll;
        curB.licksAll{ff,1} = licking.licksAll;
        curB.predSlowing(ff,1) = slowing.meanCentile/100;

        % extract true stop statistics
        for jj = 1:length(namesStopNum)
            curB.(namesStopNum{jj})(ff) =...
                behavior.stopStats.(namesStopNum{jj});
        end

        % extract try statistics
        for jj = 1:length(namesTryNum)
            curB.(namesTryNum{jj})(ff) =...
                behavior.tryStats.(erase(namesTryNum{jj},'Try'));
        end

        % extract cell based true stop statistics
        for jj = 1:length(namesStopCell)
            curB.(namesStopCell{jj}){ff} =...
                behavior.stopStats.(namesStopCell{jj});
        end

        % extract velocity statistics
        curB.avgVelMovingRaw(ff) = behavior.velStats.raw.meanVelAllMoving;
        curB.avgVelAllRaw(ff) = behavior.velStats.raw.meanVelAll;
        curB.avgVelMovingAbs(ff) = behavior.velStats.abs.meanVelAllMoving;
        curB.avgVelAllAbs(ff) = behavior.velStats.abs.meanVelAll;
        curB.perTimeStopped(ff) = behavior.velStats.perTimeStopped;
        curB.velMovingRaw{ff} = behavior.velStats.raw.velAllMoving;
        curB.velMovingAbs{ff} = behavior.velStats.abs.velAllMoving;
        curB.velDistMean{ff} = behavior.velStats.velDistMean;
        curB.dwellDistMean{ff} = behavior.velStats.dwellDistMean;

        % extract mouse and day
        curB.day{ff} = fNames{ff}(3:8);
        curB.mouse = split(mID{m},'\');

        % print file completion
        fprintf([num2str(m) '-' num2str(ff) '\n'])


    end


    %% Process multi-session statistics

    % concatenate stops per lap
    stopsPerLapAllSessions = cat(1,curB.numStopsPerLap{typeLearn})';

    % percent stops in reward (avg of first 1 or 3 days and last 3 days)
    perStopsInReward_F1 = nanmean(cat(1,curB.perStopsInReward(typeLearn(1)),1));
    perStopsInReward_F3 = nanmean(cat(1,curB.perStopsInReward(typeLearn(1:3)),1));
    perStopsInReward_L3 = nanmean(cat(1,curB.perStopsInReward(typeLearn(end-2:end)),1));

    % rolling dprime (avg of first 2 days, last 3 days, all days)
    includeIdx = find(curB.includeIdx{typeLearn(1)});
    dprimeRoll_F2 = mean(cat(1,curB.dprimeRoll{typeLearn(1:2)}),1,'omitnan');
    dprimeRoll_L3 = mean(cat(1,curB.dprimeRoll{typeLearn(end-2:end)}),1,'omitnan');
    dprimeRoll_All = mean(cat(1,curB.dprimeRoll{typeLearn(:)}),1,'omitnan');

    % rolling dprime (after versus before learning)
    dprimeRoll_F2L3 = dprimeRoll_L3-dprimeRoll_F2;

    % calculate distribution changes (stop and velocity distribution)
    for ii = 1:2
        if ii==1
            dataUse = curB.stopDist;
        elseif ii==2
            dataUse = curB.velDistMean;
        end

        F1 = nanmean(cat(1,dataUse{typeLearn(1)}),1);
        F3 = nanmean(cat(1,dataUse{typeLearn(1:3)}),1);
        L3 = nanmean(cat(1,dataUse{typeLearn(end-2:end)}),1);
        D4p = nanmean(cat(1,dataUse{typeLearn(4:end)}),1);

        % normalized change
        F1L3 = L3-F1;
        F3L3 = L3-F3;

        if ii==1
            stopDistChange_F1L3 = F1L3;
            stopDistChange_F3L3 = F3L3;
            stopDistChange_D4p = D4p;
        elseif ii==2
            velDistChange_F1L3 = F1L3;
            velDistChange_F3L3 = F3L3;
            velDistChange_D4p = D4p;
        end
    end

    % speed distribution when not stopped (raw velocity)
    [velRawKS,~] = ksdensity(cat(1,curB.velMovingRaw{typeLearn}),velBins);
    velRawKS = velRawKS*100;

    % speed distribution when not stopped (abs velocity)
    [velAbsKS,~] = ksdensity(cat(1,curB.velMovingAbs{typeLearn}),velBins);
    velAbsKS = velAbsKS*100;


    %% Calculate experience based statistics

    % maximum number of rewards to identify
    nMax = 100;

    % concatentate all successes including extra days
    successAllSessions = cat(1,curB.successPerLap{envType==2});

    % first day above learning threshold
    dGDayThresh = find(curB.dprimeGlobal(typeLearn)>dThresh,1);
    if isempty(dGDayThresh)
        dGDayThresh = length(typeLearn)+1;
    end

    % find indices of first laps
    idxFirstRewards = find(successAllSessions,nMax);
    idxFirstRewards(end+1:nMax) = length(successAllSessions);

    % number of laps to 5 and 10 rewards correct
    lapsTo5Rewards = idxFirstRewards(5);
    lapsTo10Rewards = idxFirstRewards(10);

    % percent success in next 5 runs as function of previous reward number
    idxFirst5Use = idxFirstRewards;
    idxFirst5Use(idxFirst5Use>length(successAllSessions)-5) = [];
    meanSuccess5 = movmean(successAllSessions,[0 4])*100;
    perSuccessNext5 = nan(1,nMax);
    perSuccessNext5(1:length(idxFirst5Use)) = meanSuccess5(idxFirst5Use+1);

    % percent success in next 10 runs as function of previous reward number
    idxFirst10Use = idxFirstRewards;
    idxFirst10Use(idxFirst10Use>length(successAllSessions)-10) = [];
    meanSuccess10 = movmean(successAllSessions,[0 10])*100;
    perSuccessNext10 = nan(1,nMax);
    perSuccessNext10(1:length(idxFirst10Use)) = meanSuccess10(idxFirst10Use+1);


    %% Save results

    curB.stopsPerLapAllSessions = stopsPerLapAllSessions;
    curB.perStopsInReward_F1 = perStopsInReward_F1;
    curB.perStopsInReward_F3 = perStopsInReward_F3;
    curB.perStopsInReward_L3 = perStopsInReward_L3;
    curB.dprimeRoll_F2 = dprimeRoll_F2;
    curB.dprimeRoll_L3 = dprimeRoll_L3;
    curB.dprimeRoll_All = dprimeRoll_All;
    curB.dprimeRoll_F2L3 = dprimeRoll_F2L3;
    curB.stopDistChange_F1L3 = stopDistChange_F1L3;
    curB.stopDistChange_F3L3 = stopDistChange_F3L3;
    curB.stopDistChange_D4p = stopDistChange_D4p;
    curB.velDistChange_F1L3 = velDistChange_F1L3;
    curB.velDistChange_F3L3 = velDistChange_F3L3;
    curB.velDistChange_D4p = velDistChange_D4p;
    curB.velBins = velBins;
    curB.velRawKS = velRawKS;
    curB.velAbsKS = velAbsKS;
    curB.dGDayThresh = dGDayThresh;
    curB.lapsTo5Rewards = lapsTo5Rewards;
    curB.lapsTo10Rewards = lapsTo10Rewards;
    curB.perSuccessNext5 = perSuccessNext5;
    curB.perSuccessNext10 = perSuccessNext10;

    % save current mouse data
    B(m) = curB;

    % change to parent directory
    cd(p)

end

% save combined data (match to load in next section)
save('data\allMiceDataB5.mat','B')

return


%% Set plotting parameters
% To skip recalculation, start running from here. All previously calculated
% data is loaded in allMiceData*.mat. This file name must match the current
% save output above.
%

% reclear all variables
clear; close all; clc

% reset directory
cd('D:\AD_Project\Behavior')
p = pwd;

% load processed behavioral data
load('data\allMiceDataB4.mat')

% load genotypes {[WT],[AD]}
load('groupIDs.mat')

% manually set genotypes
% groups = {[1 2 3 5 6 7 12 16 19 21],[4 8 9 10 11 13 14 15 17 18 20]};
% groups = {[1 2 3 5 6 7 12],[4 8 9 10 11 13 14]};


% define legend
legs = groupIDs;
legs4 = {'WT ref','WT recall','AD ref','AD recall'};

% define plot colors
colors = {[0 0 1],[1 0 0]};
colors4 = {[0 0 1],[0.4 0.4 1],[1 0 0],[1 0.4 0.4]};

% set day categories (FE,NE,FER,NER)
dayCats = {1:4,5:14,15,16};
nCats = length(dayCats);

% set save folder name
svFile = [p '\Figures\Figures' char(datetime('today','format','yyyyMMdd'))];
mkdir(svFile);

for nn = 1:length(sexIDs)
    mkdir([svFile '\' sexIDs{nn}])
    mkdir([svFile '\' sexIDs{nn} '\data'])
end


%% Plot line graphs by session

% define fields, titles, and labels
fields = {'perSuccess','perSuccessWithStops','perSuccessTry',...
    'dprime','dprimeWithStops','dprimeTry','dprimeGlobal','dprimeGlobalTry',...
    'successTile','successTileTry','numStops','perStopsInReward',...
    'avgVelMovingRaw','avgVelAllRaw','avgVelMovingAbs','avgVelAllAbs',...
    'perTimeStopped','predLicking','predLickingAll','predSlowing','predLickingAlt'};
ttls = {'Percent successful runs',...
    'Percent successful runs for runs with 1+ stops',...
    'Percent try runs',...
    'd'' for stops','d'' for stops for runs with 1+ stops','d'' for tries',...
    'global d'' for stops','global d'' for tries',...
    'Rolling stop success percentile for stops',...
    'Rolling stop success percentile for tries',...
    'Number of stops per session','Percent stops in reward zone',...
    'Average velocity when moving (Raw)','Average velocity (Raw)',...
    'Average velocity when moving (Abs)','Average velocity (Abs)',...
    'Percent of time spent stopped','predLicking',...
    'Predictive Licking (# pred licks/all licks)','Predicitve slowing','Predictive Licking (learning paper method)'};
ylabs = {'Percent','Percent','Percent','d''','d''','d''','Global d''',...
    'Global d''','Correct stop (%ile)','Correct stop (%ile)',...
    'Number of stops','Percent','Velocity (cm/s)','Velocity (cm/s)',...
    'Velocity (cm/s)','Velocity (cm/s)','Percent','Percent','Percent',...
    'percentile','percent'};

% plot subset of fields
plotFields = 1:length(fields);
% plotFields = [1 3 7 11 13 18];
% plotFields = [20:21];

% calculate maximum number of plotting sessions
maxSessions = max(cellfun(@length,{B(:).typeAll}));

% define sexes to plot
useSexes = 1:3;

% plot lines for individual mice
indON = 0;

% close all figures
clAll = 1;

% adjust for copying
plotNice = 1;

% define x-axis to plot
xPlot = 4:14;

nPlot = length(xPlot);
X = xPlot-4;
if xPlot(1)==4
    % if only 1 FE day, label as FE
    Xname = ['FE' string(1:nPlot-1)];
else
    % label last FE day as day 0
    Xname = xPlot-4;
end

% loop through all fields
for pf = 1%:length(plotFields)
    % loop through sexes
    for nn = 1:length(useSexes)
        %% Plot current field
        f = plotFields(pf);

        % current sexes
        curSexes = sexes{useSexes(nn)};
        curSexID = sexIDs{useSexes(nn)};

        % initialize data matrices
        curData = zeros(length(B),maxSessions);
        data = cell(1,2);

        % extract data for current field (pad data with nan)
        for ii = 1:length(B)
            curD = B(ii).(fields{f})(B(ii).typeAll);
            curD(end+1:maxSessions) = nan;
            curData(ii,:) = curD;
        end

        % sort data by group
        for g = 1:2
            data{g} = curData(intersect(groups{g},curSexes),xPlot);
        end

        % calculate p values
        pMC = nan(nPlot,1);
        pAnova = nan(nPlot,2);

        for ii = 1:nCats
            % find intersect of plotting x values with day category
            curCat = find(ismember(xPlot,dayCats{ii}));
            lenCur = length(curCat);
            if lenCur>1
                % calculate anova p values with multiple comparisons
                [pACur,pMCCur] = anovaRM2W_full_BH...
                    (data{1}(:,curCat),data{2}(:,curCat),1);
                pAnova(curCat,:) = pACur([1 3])'.*ones(lenCur,2);
            else
                % calculat single day p values
                [~,pMCCur] = ttest2(data{1}(:,curCat),data{2}(:,curCat));
            end

            pMC(curCat) = pMCCur;
        end

        % initialize figure
        figure; hold on

        % plot learning threshold for d-prime
        if ismember(f,4:8)
            yline(1.5,"--")
        end

        % plot line graph
        plotErrorSig(X,data{1},data{2},legs,pAnova,pMC,colors,indON)

        % set figure labels
        legend('Location','eastoutside')
        xlabel('Session')
        ylabel(ylabs{f})
        title([ttls{f} ' (' curSexID ')'])
        set(gca,'FontSize',12)

        % set x axis and labels
        set(gca,'XTick',X)
        set(gca,'XTickLabels',Xname)
        xlim([X(1)-0.5 X(end)+0.5])

        % save figure
        savefig([svFile '\' curSexID '\' fields{f} '_' curSexID '.fig'])

        % save data
        save([svFile '\' curSexID '\data\'  fields{f} '_' curSexID '.mat'],'xPlot','data')

        % save figure as tif if indivudual plot is on to preserve transparency
        if indON
            exportgraphics(gcf,[svFile '\' curSexID '\'  fields{f} '_' curSexID '.tif'])
        end

        % adjust for copying
        if plotNice
            axis('square')
            legend('off')
        end

        % close figure
        if clAll
            close
        end
    end
end


%% Plot recall behavior
% 4-day baseline: The last 3 training days prior to the onset of baseline
%   imaging that had auto training (no manual stopping) and had 5 or more
%   runs were averaged with Day 0.
% 1-day baseline: Only day 0 is used for basline comparison. Currently the
%   default.
%
% Raw: Unnormalized behavior on recall day. Comparison between WT and AD
% Relative-self: Recall behavior is normalized by mouse to baseline.
%   behavior. Comparison between WT and AD or comparison with 0.
% Relative-group: Recall behavior is normalized by genotype to baseline
%   behavior. Comparison between WT and AD recall or between baseline and
%   recall for per genotype.
%

fields = {'perSuccess','perSuccessWithStops','perSuccessTry',...
    'dprime','dprimeWithStops','dprimeTry','dprimeGlobal','dprimeGlobalTry',...
    'successTile','successTileTry','numStops','perStopsInReward',...
    'avgVelMovingRaw','avgVelAllRaw','avgVelMovingAbs','avgVelAllAbs',...
    'perTimeStopped','predLicking','predLickingAll','predSlowing','predLickingAlt'};
ttls = {'Percent successful runs',...
    'Percent successful runs for runs with 1+ stops',...
    'Percent try runs',...
    'd'' for stops','d'' for stops for runs with 1+ stops','d'' for tries',...
    'global d'' for stops','global d'' for tries',...
    'Rolling stop success percentile for stops',...
    'Rolling stop success percentile for tries',...
    'Number of stops per session','Percent stops in reward zone',...
    'Average velocity when moving (Raw)','Average velocity (Raw)',...
    'Average velocity when moving (Abs)','Average velocity (Abs)',...
    'Percent of time spent stopped','predLicking',...
    'Predictive Licking (# pred licks/all licks)','Predicitve slowing','Predictive Licking (learning paper method)'};
ylabs = {'Percent','Percent','Percent','d''','d''','d''','Global d''',...
    'Global d''','Correct stop (%ile)','Correct stop (%ile)',...
    'Number of stops','Percent','Velocity (cm/s)','Velocity (cm/s)',...
    'Velocity (cm/s)','Velocity (cm/s)','Percent','Percent','Percent',...
    'percentile','percent'};

% define normalization method groups and labels
normMethod = {'raw','relativeGroup'};
nNorm = length(normMethod);

% plot subset of fields
% plotFields = 1:length(fields);
plotFields = [1 3 7 11 13 18];
% plotFields = [20:21];

% define x axis labels
rXlabel = legs4;

% define legends and t-test pairs
legUse = legs4;
pShow = {[1 2;1 3;2 4;3 4],[1 2;3 4;]};

% define sexes to plot
useSexes = 1:3;

% close all figures
clAll = 0;

% loop through all fields
for f = 1:length(fields)
    % loop through sexes
    for nn = 1:length(useSexes)
        %% Plot current field

        % current sexes
        curSexes = sexes{useSexes(nn)};
        curSexID = sexIDs{useSexes(nn)};

        % initialize data matrices
        curData = zeros(length(B),2);
        data = cell(1,2);

        % extract data for current field
        for ii = 1:length(B)
            if isempty(B(ii).type{3})
                % skip mice with no recall behavior
                curData(ii,:) = nan(1,2);
            else
                % define 1-day baseline
                idxT = {(B(ii).type{1}), B(ii).type{3}};

                curD = cellfun(@(a) {B(ii).(fields{f})(a)},idxT);
                curData(ii,:) = cellfun(@nanmean,curD);
            end
        end

        % loop through normalization methods
        for ii = 1:nNorm
            %% Process Data

            % current normalization indices
            data = {};

            % loop through groups and normalize
            for g = 1:2
                if ii==1
                    normVal = 1;
                elseif ii==2
                    normVal = nanmean(curData(intersect(groups{g},curSexes),1));
                end

                data{2*(g-1)+1} = curData(intersect(groups{g},curSexes),1)/normVal;
                data{2*(g-1)+2} = curData(intersect(groups{g},curSexes),2)/normVal;
            end


            %% Plot data

            % initialize figure
            figure; hold on

            % plot bar graph
            [bh,pBar] = barGroup(rXlabel,data,colors4,pShow{ii},'pair');
            pBar;
            if ii==1
                ylabsCur = ylabs{f};
            else
                ylabsCur = 'Fold Change';
            end
            ylabel(ylabsCur)
            title([ttls{f} ': ' normMethod{ii} ' (' curSexID ')'])
            set(gca,'FontSize',12)

            % save figure
            svlab = ['recall_' fields{f} '_' normMethod{ii} '_' curSexID];
            savefig([svFile '\' curSexID '\' svlab '.fig'])

            % save data
            save([svFile '\' curSexID '\data\' svlab '.mat'],'rXlabel','data')

            % close figure
            if clAll
                close
            end
        end
    end
end


%% Plot arbitrary line graphs

% define fields, titles, and labels
fields = {'perSuccessNext5','perSuccessNext10','stopDistChange_F1L3',...
    'stopDistChange_F3L3','stopDistChange_D4p','velDistChange_F1L3',...
    'velDistChange_F3L3','velDistChange_D4p',...
    'dprimeRoll_F2','dprimeRoll_L3','dprimeRoll_All','dprimeRoll_F2L3'};
ttls = {'Percent success in next 5 runs as a function of previous reward number'...
    'Percent success in next 10 runs as a function of previous reward number',...
    'Change in velocity distribution between first 1 and last 3 days (when moving)',...
    'Change in velocity distribution between first 3 and last 3 days (when moving)',...
    'Mean velocity distribution on day 4-10 (when moving)',...
    'Change in dwell time between first 1 and last 3 days',...
    'Change in dwell time between first 3 and last 3 days',...
    'Mean dwell time distribution on day 4-10',...
    'Rolling d'' on first 2 days','Rolling d'' on last 3 days',...
    'Rolling d'' on all days','Rolling d'' between first 2 and last 3 days'};
xlabs = {'Number of previous rewards','Number of previous rewards',...
    'Track location','Track location','Track location',...
    'Track location','Track location','Track location',...
    'Track location','Track location','Track location','Track location'};
ylabs = {'Percent','Percent','Normalized percent','Normalized percent',...
    'Normalized percent','Velocity (cm/s)','Velocity (cm/s)','Velocity (cm/s)',...
    'd''','d''','d''','d'''};

% define x axis ranges
xGlobalD = B(1).includeIdx{B(1).typeLearn(1)};
% X = {1:20,1:20,0:5:600,0:5:600,0:5:600,0:5:600,0:5:600,0:5:600,...
%     xGlobalD,xGlobalD,xGlobalD,xGlobalD};
X = {1:20,1:20,0:5:600,0:5:600,0:5:600,0:5:595,0:5:595,0:5:595,...
    xGlobalD,xGlobalD,xGlobalD,xGlobalD};

% define sexes to plot
useSexes = 1:3;

% plot lines for individual mice
indON = 0;

% close all figures
clAll = 1;

% loop through all fields
for f = 1:length(fields)
    % loop through sexes
    for nn = 1:length(useSexes)
        %% Plot current field

        % current sexes
        curSexes = sexes{useSexes(nn)};
        curSexID = sexIDs{useSexes(nn)};

        % initialize data matrix
        data = cell(1,2);

        % sort data by group
        for g = 1:2
            data{g} = cat(1,B(intersect(groups{g},curSexes)).(fields{f}));
            data{g} = data{g}(:,1:length(X{f}));
        end

        if f<=2
            mcUse = 0;
        else
            mcUse = 1;
        end

        % calculate p values
        [pACur,pMC] = anovaRM2W_full_BH(data{1},data{2},mcUse);
        pAnova = pACur([1 3])'.*ones(length(X{f}),2);

        % initialize figure
        figure; hold on

        % plot line graph
        plotErrorSig(X{f},data{1},data{2},legs,pAnova,pMC,colors,indON)

        % plot reward zone and false zone for distributions
        if ismember(f,3:8)
            fill([510 510 560 560],[-0.6 2 2 -0.6],[1 1 0.7],'LineStyle','None',...
                'FaceAlpha',0.5,'DisplayName','Reward Zone')
            %
            % fill([95 95 145 145],[-0.6 2 2 -0.6],[1 0.8 0.8],'LineStyle','None',...
            %     'FaceAlpha',0.5,'DisplayName','False alarm zone')

            legend('Location','eastoutside')
        end

        % set figure labels
        xlabel(xlabs{f})
        ylabel(ylabs{f})
        title([ttls{f} ' (' curSexID ')'])
        set(gca,'FontSize',12)

        % set x axis
        xlim([X{f}(1) X{f}(end)])

        % save figure
        savefig([svFile '\' curSexID '\' fields{f} '_' curSexID '.fig'])

        % save data
        curX = X{f};
        save([svFile '\' curSexID '\data\' fields{f} '_' curSexID '.mat'],'curX','data')

        % save figure as tif if indivudual plot is on to preserve transparency
        if indON
            exportgraphics(gcf,[svFile '\' curSexID '\' fields{f} '_' curSexID '.tif'])
        end

        % close figure
        if clAll
            close
        end
    end
end


%% Plot bar graphs

% define fields, titles, and labels
fieldsD = cell(1,2);
fieldsD{1} = {'perStopsInReward_F1','perStopsInReward_F3',...
    'lapsTo5Rewards','dGDayThresh'};
fieldsD{2} = {'perStopsInReward_L3','perStopsInReward_L3',...
    'lapsTo10Rewards','dGDayThresh'};
ttls = {'Percent stops in reward zone',...
    'Percent stops in reward zone',...
    'Number of laps to 5 and 10 rewards','Days to global d'' threshold'};
Xlabs = {{'First day','Last 3 days'},{'First 3 days','Last 3 days'},...
    {'Laps to 5 rewards','Laps to 10 rewards'},{'',''}};
ylabs = {'Percent','Percent','Number of laps','Days'};
svlab = {'perStopsInReward_F1L3',...
    'perStopsInReward_F3L3','NLapsToRewards','dGDayThresh'};

% define sexes to plot
useSexes = 1:3;

% close all figures
clAll = 1;

% loop through all fields
for f = 1:length(fieldsD{1})
    % loop through sexes
    for nn = 1:length(useSexes)
        %% Plot current field

        % current sexes
        curSexes = sexes{useSexes(nn)};
        curSexID = sexIDs{useSexes(nn)};

        % initialize data matrix
        data = cell(2,2);

        % sort data by group
        for ff = 1:2
            for g = 1:2
                data{ff,g} = cat(1,B(intersect(groups{g},curSexes)).(fieldsD{ff}{f}));
            end
        end

        % set x labels
        X = Xlabs{f};

        % initialize figure
        figure; hold on

        % define t-test pairs
        pShow = [1 3;2 4];

        % plot bar graph
        [h,pBar] = barGroup(X,data,colors,pShow);

        % set figure labels
        legend(legs,'Location','eastoutside')
        legend boxoff
        ylabel(ylabs{f})
        title([ttls{f} ' (' curSexID ')'])
        set(gca,'FontSize',12)

        % save figure
        savefig([svFile '\' curSexID '\' svlab{f} '_' curSexID '.fig'])

        % save data
        save([svFile '\' curSexID '\data\' svlab{f} '_' curSexID '.mat'],'X','data')

        % close figure
        if clAll
            close
        end
    end
end


%% Plot velocity distributions

% define fields and titles
fields = {'velRawKS','velAbsKS'};
fieldX = {'velBins','velBins'};
ttls = {'Distribution of velocity when moving (Raw)',...
    'Distribution of velocity when moving (Abs)'};

% define sexes to plot
useSexes = 1:3;

% plot lines for individual mice
indON = 0;

% close all figures
clAll = 1;

% loop through all fields
for f = 1:length(fields)
    % loop through sexes
    for nn = 1:length(useSexes)
        %% Plot current field

        % current sexes
        curSexes = sexes{useSexes(nn)};
        curSexID = sexIDs{useSexes(nn)};

        % initialize data matrix
        data = cell(1,2);
        distr = cell(1,2);
        ksData = cell(1,2);

        % extract data for current field
        curField = cat(1,B(:).(fields{f}));
        X = B(1).(fieldX{f});

        velocityDist = cell(length(B),1);

        for ii = 1:length(B)
            velocityDist{ii} = cat(1,B(ii).velMovingRaw{B(ii).typeLearn});
        end

        figure; hold on
        % sort data by group
        for g = 1:2
            data{g} = curField(intersect(groups{g},curSexes),:);
            distr{g} = cat(1,velocityDist{intersect(groups{g},curSexes)});
            ksData{g} = ksdensity(distr{g},X,'Function','cdf');
            plot(X,ksData{g})
        end
        [~,pK] = kstest2(distr{1},distr{2});

        % calculate p values
        [pACur,pMC] = anovaRM2W_full_BH(data{1},data{2},0);
        % [~,pAnova] = kstest2(nanmean(data{1},1),nanmean(data{2},1));
        pAnova = pACur([1 3])'.*ones(length(pMC),2);

        % initialize figure
        figure; hold on

        % plot line graph
        plotErrorSig(X,data{1},data{2},legs,pAnova,pMC,colors,indON)

        % set figure labels
        legend('Location','eastoutside')
        xlabel('Velocity (cm/s)')
        ylabel('Percent')
        title([ttls{f} ' (' curSexID ')'])
        set(gca,'FontSize',12)

        % save figure
        savefig([svFile '\' curSexID '\' fields{f} '_' curSexID '.fig'])

        % save data
        save([svFile '\' curSexID '\data\' fields{f} '_' curSexID '.mat'],'X','data')

        % save figure as tif if indivudual plot is on to preserve transparency
        if indON
            exportgraphics(gcf,[svFile '\' curSexID '\' fields{f} '_' curSexID '.tif'])
        end

        % close figure
        if clAll
            close
        end
    end
end


%% Plot number of stops per lap

% define fields and titles
fields = {'stopsPerLapAllSessions'};
ttls = {'Number of stops per run across runs'};

% define sexes to plot
useSexes = 1:3;

% plot lines for individual mice
indON = 0;

% close all figures
clAll = 1;

% loop through all fields
for f = 1:length(fields)
    % loop through sexes
    for nn = 1:length(useSexes)
        %% Plot current field

        % current sexes
        curSexes = sexes{useSexes(nn)};
        curSexID = sexIDs{useSexes(nn)};

        % initialize data matrix
        data = cell(1,2);

        % extract data for current field
        curData = {B(:).(fields{f})};
        curMean = cellfun(@(a) mean(reshape(a,19,[]),2)',curData,'UniformOutput',0);
        curField = cat(1,curMean{:});

        % set x axis
        X = 1:size(curField,2);

        % sort data by group
        for g = 1:2
            data{g} = curField(intersect(groups{g},curSexes),:);
        end

        % calculate p values
        [pACur,pMC] = anovaRM2W_full_BH(data{1},data{2},1);
        pAnova = pACur([1 3])'.*ones(length(pMC),2);

        % initialize figure
        figure; hold on

        % plot line graph
        plotErrorSig(X,data{1},data{2},legs,pAnova,pMC,colors)

        % set figure labels
        legend('Location','eastoutside')
        xlabel('Lap Number')
        ylabel('Number of Stops')
        title([ttls{f} ' (' curSexID ')'])
        set(gca,'FontSize',12)

        % save figure
        savefig([svFile '\' curSexID '\' fields{f} '_' curSexID '.fig'])

        % save data
        save([svFile '\' curSexID '\data\' fields{f} '_' curSexID '.mat'],'X','data')

        % save figure as tif if indivudual plot is on to preserve transparency
        if indON
            exportgraphics(gcf,[svFile '\' curSexID '/' fields{f} '_' curSexID '.tif'])
        end

        % close figure
        if clAll
            close
        end
    end
end


%% Plot correlations

% define fields, titles, and labels
field1 = {'perSuccess','perSuccess','perSuccess'};
field2 = {'perSuccessTry','dprimeGlobal','predLicking'};

% set group to correlate
groupsCorr = groups;

% define sexes to plot
useSexes = 1:3;

% close all figures
clAll = 1;

% loop through all fields
for f = 1:length(field1)
    % loop through sexes
    for nn = 1:length(useSexes)
        %% Plot current field

        % current sexes
        curSexes = sexes{useSexes(nn)};
        curSexID = sexIDs{useSexes(nn)};

        groupsCur = cell(size(groupsCorr));
        for g = 1:length(groupsCorr)
            groupsCur{g} = intersect(groupsCorr{g},curSexes);
        end

        % initialize data matrices
        curData1 = zeros(length(B),length(B(1).typeLearn));
        curData2 = zeros(length(B),length(B(1).typeLearn));
        data = cell(1,2);

        % extract data for current field (pad data with nan)
        for ii = 1:length(B)
            % extract field 1 data
            curD = B(ii).(field1{f})(B(ii).typeLearn);
            curData1(ii,:) = curD;

            % extract field 2 data
            curD = B(ii).(field2{f})(B(ii).typeLearn);
            curData2(ii,:) = curD;
        end

        data1 = curData1(cat(2,groupsCur{:}),:)';
        data1 = data1(:);
        data2 = curData2(cat(2,groupsCur{:}),:)';
        data2 = data2(:);

        % calculate linear correlation
        [rCorr,pCorr] = corr(data1,data2);


        %% Plot figure

        % initialize figure
        figure; hold on

        % plot scatter (currently valid for up to 2 groups)
        nDays = size(curData1,2);
        for ii = 1:length(groupsCur)
            startIdx = length(groupsCur{1})*nDays*(ii-1)+1;
            stopIdx = startIdx+length(groupsCur{ii})*nDays-1;
            scatter(data1(startIdx:stopIdx),data2(startIdx:stopIdx),...
                25,colors{ii})
        end

        % set figure labels
        xlabel(field1{f})
        ylabel(field2{f})
        title(['Correlation: ' field1{f} ' vs. ' field2{f}...
            '; r=' num2str(rCorr,2) ', p=' num2str(pCorr,2) ' (' curSexID ')'])
        set(gca,'FontSize',12)
        axis('square')

        % save figure
        savefig([svFile '\' curSexID '\Corr_' field1{f} '-' field2{f} '_' curSexID '.fig'])

        % save data
        save([svFile '\' curSexID '\data\Corr_' field1{f} '-' field2{f} '_' curSexID '.mat'],'data1','data2')

        % close figure
        if clAll
            close
        end
    end
end


%% Plot lick distribution

% define fields, titles, and labels
fields = {'licksAll'};
ttls = {'Lick distribution'};
ylabs = {'Probability density'};

% define sexes to plot
useSexes = 1:3;

% close all figures
clAll = 1;

% define x-axis to plot
xPlot = 0:2.5:600;

% loop through all fields
for f = 1:length(fields)
    % loop through sexes
    for nn = 1:length(useSexes)
        %% Plot current field

        % current sexes
        curSexes = sexes{useSexes(nn)};
        curSexID = sexIDs{useSexes(nn)};

        % initialize data matrices
        curData = cell(length(B),1);
        data = cell(1,2);
        dataKS = cell(1,2);

        % extract data for current field
        for ii = 1:length(B)
            curD = B(ii).(fields{f})(B(ii).typeLearn);
            curData{ii} = cat(1,curD{:});
        end

        % sort data by group
        for g = 1:2
            data{g} = curData(intersect(groups{g},curSexes));
            dataKS{g} = zeros(length(intersect(groups{g},curSexes)),length(xPlot));
            for kk = 1:length(intersect(groups{g},curSexes))
                dataKS{g}(kk,:) = ksdensity(data{g}{kk},xPlot);
            end
        end

        % calculate p values
        [pACur,pMC] = anovaRM2W_full_BH(dataKS{1},dataKS{2},0);
        % [~,pAnova] = kstest2(nanmean(dataKS{1},1)',nanmean(dataKS{2},1)');
        pAnova = pACur([1 3])'.*ones(length(pMC),2);

        % initialize figure
        figure; hold on

        % plot line graph
        plotErrorSig(xPlot,dataKS{1},dataKS{2},legs,pAnova,pMC,colors)

        % set figure labels
        legend('Location','eastoutside')
        xlabel('Session')
        ylabel(ylabs{f})
        title([ttls{f} ' (' curSexID ')'])
        set(gca,'FontSize',12)

        % plot reward zone and false zone for distributions
        yPK = max(ylim);
        fill([510 510 560 560],[0 yPK yPK 0],[1 1 0.7],'LineStyle','None',...
            'FaceAlpha',0.5,'DisplayName','Reward Zone')
        legend('Location','eastoutside')

        % set x axis and labels
        xlim([0 600])

        % save figure
        savefig([svFile '\' curSexID '\' fields{f} '_' curSexID '.fig'])

        % save data
        save([svFile '\' curSexID '\data\' fields{f} '_' curSexID '.mat'],'xPlot','data')

        % close figure
        if clAll
            close
        end
    end
end


%% Plot stop distributions

% define fields, titles, and labels
% fields = {'stopTimeDist'};
% ttls = {'Stop time distribution: post-learning (all stops)'};
% ylabs = {'Time spent stopped (sec)'};

fields = {'stopTimeDist','stopTimeDist_NPR',...
    'yStartDistribution','yStartDistribution_NPR'};
ttls = {'Stop time distribution: post-learning (all stops)',...
    'Stop time distribution: post-learning (no post-reward stops)',...
    'Stop distribution: post-learning (all stops)',...
    'Stop distribution: post-learning (no post-reward stops)'};
ylabs = {'Time spent stopped (sec)','Time spent stopped (sec)',...
    'Fraction of laps with stop','Fraction of laps with stop'};

useDays = 10:14;

% define sexes to plot
useSexes = 1:3;

% close all figures
clAll = 1;

% define x-axis to plot
xPlot = 0:5:600;

% xZones = {(20:5:475)/5,(480:5:560)/5};
xZones = {(20:5:480)/5,(510:5:560)/5};

% loop through all fields
for f = 1:length(fields)
    % loop through sexes
    for nn = 1:length(useSexes)
        %% Plot current field

        % current sexes
        curSexes = sexes{useSexes(nn)};
        curSexID = sexIDs{useSexes(nn)};

        % initialize data matrices
        curDataMean = cell(length(B),1);
        data = cell(1,2);

        % extract data for current field
        for ii = 1:length(B)
            curData = B(ii).(fields{f})(B(ii).typeAll);
            curDataCat = cat(1,curData{useDays});
            curDataMean{ii} = mean(curDataCat,1,'omitnan');
        end

        % sort data by group
        for g = 1:2
            data{g} = cat(1,curDataMean{intersect(groups{g},curSexes)});
        end

        % calculate p values
        [pACur,pMC] = anovaRM2W_full_BH(data{1},data{2},0);
        pAnova = pACur([1 3])'.*ones(length(pMC),2);

        % initialize figure
        figure; hold on

        % plot line graph
        plotErrorSig(xPlot,data{1},data{2},legs,pAnova,pMC,colors)

        % set figure labels
        legend('Location','eastoutside')
        xlabel('Track Position (cm)')
        ylabel(ylabs{f})
        title([ttls{f} ' (' curSexID ')'])
        set(gca,'FontSize',12)

        % plot reward zone and false zone for distributions
        yPK = max(ylim);
        fill([510 510 560 560],[0 yPK yPK 0],[1 1 0.7],'LineStyle','None',...
            'FaceAlpha',0.5,'DisplayName','Reward Zone')
        legend('Location','eastoutside')

        % set x axis and labels
        xlim([0 600])

        % save figure
        savefig([svFile '\' curSexID '\' fields{f} '_' curSexID '.fig'])

        % save data
        save([svFile '\' curSexID '\data\' fields{f} '_' curSexID '.mat'],'xPlot','data')

        % close figure
        if clAll
            close
        end

        %% Plot discrimination

        if f==4

            % calculate discrimination
            distMean = cell(length(xZones),2);
            distEnrich = cell(1,2);
            for g = 1:2
                for z = 1:2
                    distMean{z,g} = mean(data{g}(:,xZones{z}),2,'omitnan');
                end

                distEnrich{g} = (distMean{2,g}-distMean{1,g})./(distMean{2,g}+distMean{1,g});
            end

            % initialize figure
            figure; hold on

            % plot discrimination
            barGroup(groupIDs,distEnrich,colors,[1 2])

            % set figure info
            title(['Reward Zone Stop Enrichment' ' (' curSexID ')'])
            ylabel('Reward Zone Stop Enrichment (R-O)/(R+O)')
            ylim([0 1])
            set(gca,'FontSize',12)

            % save figure
            savefig([svFile '\' curSexID '\' fields{f} '_enrichment_' curSexID '.fig'])

            % save data
            save([svFile '\' curSexID '\data\' fields{f} '_enrichment_' curSexID '.mat'],'groupIDs','distEnrich')

            % close figure
            if clAll
                close
            end

            % calculate one-sample t-test
            for g = 1:2
                [~,pCur] = ttest(distEnrich{g},0);
                disp(pCur)
            end
        end

    end
end

