%%  plotBehaviorForFigs
% Based on behaviorAD_all, which should be run first to generate the proper
% precursor data. Plots the graphs to be used for the AD paper formatted
% specifically for the paper. Statistics and legends should be added after
% the fact based on the original plots from behaviorAD_all (to avoid issues
% with combining by sex).
%
% Plots include:
%
% Calculates and plots the behavioral parameters for the comparison of WT
% and AD mice in a 6m active learning task. Can be adapted to any active
% learning task by modifying initialization parameters and how
% "fileTypes.mat" is processed. Virmen file categories are loaded from
% fileType.mat, which is generated by defineFiles.m.
%
% Analysis Days include:
%   1. Percent success, global d', and predicitive licking time courses
%       All mice (1 plot) and female/male mice (1 plot)
%   2. Percent try, number of stops per session, mean velocity while moving
%       time course (all mice)
%   3. Percent success learning curve
%   4. Days to global d' threshold
%   5. Recall behavior (details TBD)
%


%% Load behavior data
% To skip recalculation, start running from here. All previously calculated
% data is loaded in allMiceData*.mat. This file name must match the current
% save output above.
%

% clear all variables
clear; close all; clc

% reset directory
cd('D:\AD_Project\Behavior')
p = pwd;

% load processed behavioral data
load('data/allMiceDataB5.mat')

% load correlation data
load('data/corrData.mat')

% load genotypes and sexes
load('groupIDs.mat')

% define legend
legs = groupIDs;
legs4 = {'WT ref','WT recall','AD ref','AD recall'};
nGroups = length(groups);
nSexes = length(sexes);

% define sex groups
sGroups = {1,[2 3]};
sSvLabels = {'all','bySex'};
nSGroups = length(sGroups);

% define plot colors
colors = {[0 0 1],[1 0 0]};
colors4 = {[0 0 1],[0.4 0.4 1],[1 0 0],[1 0.4 0.4]};

% sefine color shift by sex
colShift = [1 0.5];

% set day categories (FE,NE,FER,NER)
dayCats = {1:4,5:14,15,16};
nCats = length(dayCats);

% set save folder name
svFile = [p '/Figures/FY2025Figures'];

if ~isfolder(svFile)
    mkdir(svFile);
    for ss = 1:nSGroups
        mkdir([svFile '/' sSvLabels{ss}])
        mkdir([svFile '/' sSvLabels{ss} '/data'])
    end
end

% close all figures
clAll = 1;


%% Plot line graphs by session

% define fields, titles, and labels
fields = {'perSuccess','perSuccessTry','dprimeGlobal','numStops',...
    'avgVelMovingRaw','predLicking'};
ttls = {'Percent successful runs','Percent try runs','global d''',...
    'Number of stops per session','Average velocity when moving',...
    'Predictive Licking'};
ylabs = {'Percent','Percent','Global d''','Number of stops',...
    'Velocity (cm/s)','Percent'};
yLims = [0, 110; 0, 110; -0.5, 4; 0, 200; 0, 40; -5 110];

% plot subset of fields
plotFields = 1:length(fields);

% calculate maximum number of plotting sessions
maxSessions = max(cellfun(@length,{B(:).typeAll}));

% set d' threshold and field number
dFieldIdx = 3;
dThresh = 1.0;

% define x-axis to plot
xPlot = 4:14;
X = xPlot-4;
Xname = ['FE' string(1:length(X)-1)];

% define stat parameters
statCats = {1,2:11};
nStatCats = length(statCats);
corrX = 2:length(X);

% plot lines for individual mice
indON = 0;

% loop through all fields
for pf = 1:length(plotFields)
    % load current field data
    f = plotFields(pf);

    % initialize data matrices
    curData = zeros(length(B),maxSessions);

    % extract data for current field (pad data with nan)
    for ii = 1:length(B)
        curD = B(ii).(fields{f})(B(ii).typeAll);
        curD(end+1:maxSessions) = nan;
        curData(ii,:) = curD;
    end

    % loop through sex groups
    for sg = 1:nSGroups
        % initialize figure
        figure; hold on

        % plot learning threshold for d-prime
        if ismember(f,dFieldIdx)
            yline(dThresh,"--")
        end

        % loop through sexes
        for ss = 1:length(sGroups{sg})
            %% Plot current field

            % current sexes
            curSexes = sexes{sGroups{sg}(ss)};

            % sort data by group for current sex
            data = cell(1,2);
            for gg = 1:nGroups
                data{gg} = curData(intersect(groups{gg},curSexes),xPlot);
            end

            % calculate mean and SEM
            dataMean = cellfun(@(x) mean(x,1,'omitnan'),data,'UniformOutput',false);
            dataSEM = cellfun(@(x) nansem(x,1),data,'UniformOutput',false);

            % plot data
            for gg = 1:nGroups
                errorbar(X,dataMean{gg},dataSEM{gg},'Color',colors{gg}*colShift(ss))
            end

            % set figure labels
            xlabel('Session')
            ylabel(ylabs{f})
            title([ttls{f} ' (' sSvLabels{sg} ')'])
            set(gca,'FontSize',12)

            % set x axis and labels
            set(gca,'XTick',X)
            set(gca,'XTickLabels',Xname)
            xlim([X(1)-0.5 X(end)+0.5])
            ylim(yLims(pf,:))
            set(gca,'FontSize',25)
            axis('square')


            %% Calculate statistics

            statsData = struct();

            % calculate temporal correlation
            for gg = 1:nGroups
                [curR,curP] = corr(corrX',dataMean{gg}(corrX)');
                statsData.rCorr(gg) = curR;
                statsData.pCorr(gg) = curP;
            end

            % calculate ANOVA and multiple comparisons
            pMC = nan(length(X),1);
            pAnova = nan(length(X),2);
            for ii = 1:nStatCats
                % find intersect of plotting x values with day category
                curCat = statCats{ii};
                lenCur = length(curCat);
                if lenCur>1
                    % calculate anova p values with multiple comparisons
                    [pACur,pMCCur] = anovaRM2W_full_BH...
                        (data{1}(:,curCat),data{2}(:,curCat),1);
                    pAnova(curCat,:) = pACur([1 3])'.*ones(lenCur,2);
                else
                    % calculat single day p values
                    [~,pMCCur] = ttest2(data{1}(:,curCat),data{2}(:,curCat));
                end

                pMC(curCat) = pMCCur;
            end
            statsData.pAnova = pAnova;
            statsData.pMC = pMC;

            % save data
            save([svFile '/' sSvLabels{sg} '/data/'  fields{f} '_' sexIDs{sGroups{sg}(ss)} '.mat'],'xPlot','data','statsData')
        end
        % save figure
        savefig([svFile '/' sSvLabels{sg} '/' fields{f} '_' sSvLabels{sg} '.fig'])

        % close figure
        if clAll
            close
        end
    end
end


%% Plot bar graphs

% define fields, titles, and labels
fields = {'dGDayThresh'};
ttls = {'Days to global d'' threshold'};
Xlabs = {{'WT','PS19'}};
ylabs = {'Days'};
svlab = {'dGDayThresh'};
yLims = [0 14];

% define sexes to plot
useSexes = 1:3;

% close all figures
clAll = 0;

% initialize stats parameters and array
outStats = {};
nUnits = 'mice';
testName = 'two-tailed unpaired Students t-test';
testPair = 0;
testMC = 0;
testLimitP = 0;

% loop through all fields
for f = 1:length(fields)
    % loop through sexes
    statData = {};
    for ss = [1 3 2]
        %% Plot current field

        % current sexes
        curSexes = sexes{useSexes(ss)};
        curSexID = sexIDs{useSexes(ss)};

        % initialize data matrix
        data = cell(1,2);

        % sort data by group
        for gg = 1:2
            data{gg} = cat(1,B(intersect(groups{gg},curSexes)).(fields{f}));
        end

        % set x labels
        X = Xlabs{f};

        % initialize figure
        figure; hold on

        % define t-test pairs
        pShow = [1 2];

        % plot bar graph
        [h,pBar] = barGroup(X,data,'violin',colors,pShow);

        % set figure labels
        ylabel(ylabs{f})
        ylim(yLims(f,:))
        title([ttls{f} ' (' curSexID ')'])
        set(gca,'FontSize',12)

        % save figure
        if ~isfolder([svFile '/' curSexID])
            mkdir([svFile '/' curSexID])
            mkdir([svFile '/' curSexID '/data'])
        end
        savefig([svFile '/' curSexID '/' svlab{f} '_' curSexID '.fig'])

        % save data
        save([svFile '/' curSexID '/data/' svlab{f} '_' curSexID '.mat'],'X','data')

        % close figure
        if clAll
            close
        end

        % store stat data
        statData(:,ss) = data;
    end

    % calculate full statistics
    testCat = fields{f};
    outStats(end+1,:) = [testCat ttestEffectSize(statData(1,:),statData(2,:),testName,nUnits,testPair,testMC,testLimitP)];

end


%% Learning rate curve

% define fields, titles, and labels
ttls = 'Percent successful runs';
ylabs = 'Percent of runs';
yLims = [0, 100];

% define fit parameters
yMin = [8.022; 0; 11.57];       % y0
yMax = [94.33; 89.69; 100.0];   % Plateau
WT_95 = [7.079; 5.633; 8.171];  % WT 95th percentile
K = [0.4232,0.1100; 0.5218,0.2221; 0.3666,0.06436]; % K for WT/PS19

for ss = 1:nSexes
    % load data
    if ss==1
        load('D:\AD_Project\Behavior/Figures/FY2025Figures/all/data/perSuccess_all.mat')
    else
        load(['D:\AD_Project\Behavior/Figures/FY2025Figures/bySex/data/perSuccess_'...
            sexIDs{ss} '.mat'])
    end

    % calculate mean and SEM
    dataMean = cellfun(@(x) mean(x(:,2:end),1,'omitnan'),data,'UniformOutput',false);

    % define x-axis to plot
    X = 1:10;
    Xname = string(X);
    Xfit = 0:11;

    % plot data
    figure; hold on

    for gg = 1:nGroups
        % plot original data
        plot(X,dataMean{gg},'Color',colors{gg},'Marker','.','MarkerSize',20)

        % plot fit
        Y = yMin(ss) + (yMax(ss)-yMin(ss))*(1-exp(-K(ss,gg)*Xfit));
        plot(Xfit,Y,'Color',colors{gg}*.5,'LineStyle','-')
    end

    % plot fit lines
    yline(yMin(ss))
    yline(yMax(ss))
    xline(WT_95(ss))

    % set figure labels
    xlabel('NE Session')
    ylabel(ylabs)
    title([ttls ' (' sexIDs{ss} ')'])
    set(gca,'FontSize',12)

    % set x axis and labels
    set(gca,'XTick',X)
    set(gca,'XTickLabels',Xname)
    xlim([X(1)-0.5 X(end)+0.5])
    ylim(yLims)
    set(gca,'FontSize',25)
    axis('square')

    % save figure
    savefig([svFile '/' sSvLabels{min(ss,2)} '/learningRate_success_' sexIDs{ss} '.fig'])

end


%% Plot behavior correlations

% define fields, titles, and labels
field1 = {'perSuccess','perSuccess','perSuccess'};
field2 = {'dprimeGlobal','predLicking','avgVelMovingRaw'};

% initialize stats parameters and array
outStats = {};
nUnits = 'behavior sessions';
testName = 'two-tailed Pearson linear correlation';

% loop through all fields
for f = 1:length(field1)
    %% Plot current field

    % initialize data matrices
    curData1 = zeros(length(B),length(B(1).typeLearn));
    curData2 = zeros(length(B),length(B(1).typeLearn));
    data = cell(1,2);

    % extract data for current field (pad data with nan)
    for ii = 1:length(B)
        % extract field 1 data
        curD = B(ii).(field1{f})(B(ii).typeLearn);
        curData1(ii,:) = curD;

        % extract field 2 data
        curD = B(ii).(field2{f})(B(ii).typeLearn);
        curData2(ii,:) = curD;
    end

    data1 = curData1(cat(2,groups{:}),:)';
    data1 = data1(:);
    data2 = curData2(cat(2,groups{:}),:)';
    data2 = data2(:);

    % calculate linear correlation
    [rCorr,pCorr] = corr(data1,data2);

    % calculate full statistics
    testCat = [field1{f} '-' field2{f}];
    outStats(end+1,:) = [testCat corrEffectSize(data1,data2,testName,nUnits)];


    %% Plot figure

    % initialize figure
    figure; hold on

    % plot scatter (currently valid for up to 2 groups)
    nDays = size(curData1,2);
    for ii = 1:length(groups)
        startIdx = length(groups{1})*nDays*(ii-1)+1;
        stopIdx = startIdx+length(groups{ii})*nDays-1;
        scatter(data1(startIdx:stopIdx),data2(startIdx:stopIdx),...
            25,colors{ii},'filled')
    end

    % set figure labels
    xlabel(field1{f})
    ylabel(field2{f})
    title(['Correlation: ' field1{f} ' vs. ' field2{f}...
        '; r=' num2str(rCorr,2) ', p=' num2str(pCorr,2) ' (' sexIDs{1} ')'])
    set(gca,'FontSize',12)
    axis('square')

    % save figure
    savefig([svFile '/all/Corr_' field1{f} '-' field2{f} '_' sexIDs{1} '.fig'])

    % save data
    save([svFile '/all/data/Corr_' field1{f} '-' field2{f} '_' sexIDs{1} '.mat'],'data1','data2')

    % close figure
    if clAll
        close
    end
end


%%

% nStops = B(12).numStopsPerLap{B(12).type{3}};
%
% % probability of not- triggering reward
% pBase = 1-50/600
%
% % probability that stops will collectively trigger a reward
% pLaps = 1-pBase.^nStops;
% pChance = mean(pLaps);



